In [6]:
#find local directory
getwd()

#set working directory
setwd("/home/user/EDS_Capstone_Project/US_Renewable_Energy_EDS_Capstone/US_Renewable_Energy_EDS_Capstone/Lesson_1:Cleaning_Data_for_Analysis")
getwd()

#set main file path
file_path <- '/home/user/EDS_Capstone_Project/US_Renewable_Energy_EDS_Capstone/US_Renewable_Energy_EDS_Capstone/Lesson_1:Cleaning_Data_for_Analysis'
file_path

[1] "/home/user/EDS_Capstone_Project/US_Renewable_Energy_EDS_Capstone/US_Renewable_Energy_EDS_Capstone/Lesson_1:Cleaning_Data_for_Analysis"

[1] "/home/user/EDS_Capstone_Project/US_Renewable_Energy_EDS_Capstone/US_Renewable_Energy_EDS_Capstone/Lesson_1:Cleaning_Data_for_Analysis"

[1] "/home/user/EDS_Capstone_Project/US_Renewable_Energy_EDS_Capstone/US_Renewable_Energy_EDS_Capstone/Lesson_1:Cleaning_Data_for_Analysis"

In [37]:
#load in packages
library(tidyverse)

#load in raw data
political_party <- read.csv(file.path(file_path, "cleaned_datasets/State_Political_Party.csv"))
energy_consumption <- read.csv(file.path(file_path, "cleaned_datasets/State_Energy_Consumptions.csv"))
yearly_policies <- read.csv(file.path(file_path, "cleaned_datasets/State_Yearly_Policies.csv"))

In [38]:
#look at data
head(political_party)
head(energy_consumption)
head(yearly_policies)

  X State Year Political_Party
1 1 AK    2002 Republican to Democratic
2 2 AK    2002 Republican to Democratic
3 3 AK    2014 Independent to Republican
4 4 AK    2014 Independent to Republican
5 5 AL    2003 Republican to Democratic
6 6 AL    2003 Republican to Democratic

  X State Year Total_Energy NonRenewable_Energy Perc_NonRenewable_Energy
1 1 AK    1960 59303        54633               92
2 2 AK    1961 70020        64860               93
3 3 AK    1962 76642        71359               93
4 4 AK    1963 78488        72995               93
5 5 AK    1964 82793        76965               93
6 6 AK    1965 85319        79262               93
  Renewable_Energy Perc_Renewable_Energy
1 4670             8
2 5160             7
3 5283             7
4 5493             7
5 5828             7
6 6057             7

  X State Year New_Policies Cumulative_Policies
1 1 AK    2000 2             2
2 2 AK    2005 1             3
3 3 AK    2006 3             6
4 4 AK    2008 1             7
5 5 AK    2009 1             8
6 6 AK    2010 2            10

In [39]:
all_energy <- political_party %>%
    inner_join(energy_consumption, by = c("State", "Year")) %>%
    select(State, Year, Political_Party, Total_Energy, NonRenewable_Energy, Perc_NonRenewable_Energy, Renewable_Energy, Perc_Renewable_Energy) %>%
    distinct()

all_energy

#checks for NAs
#all_data_NAs <- all_data[!complete.cases(all_data), ]
#all_data_NAs

   State Year Political_Party           Total_Energy NonRenewable_Energy
1  AK    2002 Republican to Democratic   723166       714640
2  AK    2014 Independent to Republican  585727       574204
3  AL    2003 Republican to Democratic  1897040      1697326
4  AR    2007 Democrat to Republican    1108782      1007996
5  AR    2015 Republican to Democrat    1043382       935957
6  AZ    2003 Democrat to Republican    1319572      1282888
7  AZ    2004 Democrat to Republican    1372363      1336001
8  AZ    2005 Democrat to Republican    1411695      1361810
9  AZ    2006 Republican to Democrat    1457800      1406575
10 AZ    2007 Republican to Democrat    1466903      1412312
11 AZ    2008 Republican to Democrat    1433406      1368820
12 AZ    2009 Republican to Democrat    1351254      1296636
13 CA    2003 Republican to Democrat    7454129      7047478
14 CA    2011 Democrat to Republican    7186089      6644859
15 CO    2007 Democratic to Republican  1463502      1432496
16 CT    2011 Democrat to Republican     740235       700295
17 DE    2017 Democratic to Democrat     274259       267191
18 FL    1999 Republican to Democratic  3907612      3704371
19 GA    2003 Republican to Democratic  2923139      2729218
20 HI    2002 Republican to Democrat     283505       274199
21 HI    2010 Democrat to Republican     293799       279414
22 HI    2014 Democratic to Democrat     285390       267004
23 IA    2011 Republican to Democratic  1441350      1161217
24 IL    2003 Democrat to Republican    3944694      3818726
25 IL    2015 Republican to Democrat    3870603      3668613
26 IN    2005 Republican to Democrat    2921512      2860635
27 KS    2003 Democrat to Republican    1137937      1118568
28 KS    2011 Republican to Democrat    1074483      1017054
29 KY    2003 Republican to Democratic  1895859      1851865
30 KY    2007 Democratic to Republican  2031787      1977072
⋮  ⋮     ⋮    ⋮                         ⋮            ⋮
65 OK    2011 Republican to Democratic  1537902      1468307
66 PA    2003 Democratic to Republican  3943918      3856561
67 PA    2011 Republican to Democratic  3727655      3547695
68 PA    2015 Democratic to Republican  3873641      3676861
69 RI    2011 Democratic to Republican   185462       178584
70 SC    2003 Republican to Democratic  1585456      1506238
71 TN    2003 Democratic to Republican  2165119      2061495
72 TN    2011 Republican to Democratic  2115408      1985161
73 VA    1999 Democratic to Republican  2286540      2168356
74 VA    2000 Democratic to Republican  2392470      2280257
75 VA    2001 Democratic to Republican  2322159      2233494
76 VA    2002 Democratic to Republican  2345733      2269429
77 VA    2010 Republican to Democratic  2498119      2363289
78 VA    2011 Republican to Democratic  2378679      2248261
79 VA    2012 Republican to Democratic  2319180      2189022
80 VA    2013 Republican to Democratic  2390087      2243007
81 VA    2014 Democratic to Republican  2445751      2282335
82 VA    2015 Independent to Democratic 2407419      2243898
83 VA    2016 Independent to Democratic 2385837      2225789
84 VA    2017 Independent to Democratic 2363063      2203852
85 VA    2018 Democratic to Independent 2454395      2283081
86 VA    2019 Democratic to Independent 2422690      2264663
87 VT    2003 Republican to Democratic   146619       130384
88 VT    2011 Democratic to Republican   145839       121977
89 WI    2003 Democratic to Republican  1849371      1744111
90 WI    2011 Republican to Democratic  1767437      1602665
91 WV    2001 Democratic to Republican   726547       717964
92 WV    2017 Republican to Democratic   742075       711474
93 WY    2003 Democratic to Republican   459188       453995
94 WY    2011 Republican to Democratic   543253       518268
   Perc_NonRenewable_Energy Renewable_Energy Perc_Renewable_Energy
1  99                         8526            1
2  98                        11523            2
3  89                       199714           11
4  91                       100786            9
5  90                       107425           10
6  97                        36684            3
7  97                        36362            3
8  96                        49885            4
9  96                        51225            4
10 96                        54591            4
11 95                        64586            5
12 96                        54618            4
13 95                       406651            5
14 92                       541230            8
15 98                        31006            2
16 95                        39940            5
17 97                         7068            3
18 95                       203241            5
19 93                       193921            7
20 97                         9306            3
21 95                        14385            5
22 94                        18386            6
23 81                       280133           19
24 97                       125968            3
25 95                       201990            5
26 98                        60877            2
27 98                        19369            2
28 95                        57429            5
29 98                        43994            2
30 97                        54715            3
⋮  ⋮                        ⋮                ⋮
65 95                        69595            5
66 98                        87357            2
67 95                       179960            5
68 95                       196780            5
69 96                         6878            4
70 95                        79218            5
71 95                       103624            5
72 94                       130247            6
73 95                       118184            5
74 95                       112213            5
75 96                        88665            4
76 97                        76304            3
77 95                       134830            5
78 95                       130418            5
79 94                       130158            6
80 94                       147080            6
81 93                       163416            7
82 93                       163521            7
83 93                       160048            7
84 93                       159211            7
85 93                       171314            7
86 93                       158027            7
87 89                        16235           11
88 84                        23862           16
89 94                       105260            6
90 91                       164772            9
91 99                         8583            1
92 96                        30601            4
93 99                         5193            1
94 95                        24985            5

In [25]:
write.csv(all_energy, file.path(file_path, "/cleaned_datasets/State_PolParty_Energy.csv"))

In [35]:
all_YearlyPolicies <- political_party %>%
    inner_join(yearly_policies, by = c("State", "Year")) %>%
    select(State, Year, Political_Party, New_Policies, Cumulative_Policies) %>%
    distinct()

all_YearlyPolicies

   State Year Political_Party                            New_Policies
1  AK    2014 Independent to Republican                   1
2  AR    2015 Republican to Democrat                      2
3  AZ    2003 Democrat to Republican                      1
4  AZ    2004 Democrat to Republican                      1
5  AZ    2005 Democrat to Republican                      1
6  AZ    2006 Republican to Democrat                      4
7  AZ    2007 Republican to Democrat                      4
8  AZ    2008 Republican to Democrat                      6
9  AZ    2009 Republican to Democrat                      4
10 CA    2011 Democrat to Republican                     13
11 CO    2007 Democratic to Republican                    5
12 CT    2011 Democrat to Republican                      2
13 GA    2003 Republican to Democratic                    2
14 HI    2010 Democrat to Republican                      2
15 IA    2011 Republican to Democratic                    1
16 IN    2005 Republican to Democrat                      1
17 KY    2007 Democratic to Republican                    2
18 KY    2015 Republican to Democratic                    2
19 LA    2004 Democratic to Republican                    1
20 LA    2016 Democratic to Republican                    1
21 MA    2007 Democratic to Republican                    3
22 MA    2015 Republican to Democratic                    2
23 MD    2007 Democratic to Republican                    2
24 MD    2015 Republican to Democratic                    7
25 ME    2003 Democratic to Independent                   1
26 ME    2011 Republican to Democratic                    1
27 MI    2003 Democratic to Republican                    1
28 MI    2011 Republican to Democratic                    2
29 MN    2003 Republican to Minnesota Independence Party  1
30 MN    2011 Democratic-Farmer-Labor to Republican       5
31 MO    2009 Democratic to Republican                    3
32 MS    2000 Democratic to Republican                    1
33 MT    2005 Democratic to Republican                    2
34 NC    2013 Republican to Democratic                    1
35 NJ    2010 Republican to Democratic                    4
36 NM    2003 Democratic to Republican                    1
37 NM    2011 Republican to Democratic                    2
38 NY    2007 Democratic to Republican                    3
39 OH    2007 Democratic to Republican                    2
40 OH    2011 Republican to Democratic                    3
41 OK    2011 Republican to Democratic                    4
42 PA    2003 Democratic to Republican                    1
43 PA    2011 Republican to Democratic                    4
44 PA    2015 Democratic to Republican                    2
45 RI    2011 Democratic to Republican                    1
46 TN    2011 Republican to Democratic                    1
47 VA    2000 Democratic to Republican                    2
48 VA    2001 Democratic to Republican                    1
49 VA    2010 Republican to Democratic                    5
50 VA    2011 Republican to Democratic                    4
51 VA    2012 Republican to Democratic                    1
52 VA    2014 Democratic to Republican                    2
53 VA    2015 Independent to Democratic                   5
54 VA    2016 Independent to Democratic                   3
55 WI    2003 Democratic to Republican                    1
56 WI    2011 Republican to Democratic                    3
57 WV    2001 Democratic to Republican                    2
58 WY    2003 Democratic to Republican                    2
59 WY    2011 Republican to Democratic                    2
   Cumulative_Policies
1    12
2    53
3    72
4    69
5    70
6    76
7    80
8    86
9    90
10  203
11  295
12  400
13  557
14  617
15  659
16  769
17  851
18  862
19  875
20  888
21  929
22  946
23 1050
24 1022
25 1066
26 1075
27 1094
28 1128
29 1156
30 1250
31 1301
32 1330
33 1360
34 1427
35 1545
36 1576
37 1595
38 1651
39 1733
40 1753
41 1777
42 1900
43 1930
44 1933
45 1982
46 2063
47 2261
48 2266
49 2244
50 2248
51 2273
52 2250
53 2255
54 2276
55 2446
56 2470
57 2488
58 2496
59 2511

In [36]:
write.csv(all_YearlyPolicies, file.path(file_path, "/cleaned_datasets/State_PolParty_YearlyPol.csv"))