In [3]:
#find local directory
getwd()

#set working directory
setwd("/home/user/EDS_Capstone_Project/US_Renewable_Energy_EDS_Capstone/US_Renewable_Energy_EDS_Capstone/Lesson_1:Cleaning_Data_for_Analysis")
getwd()

#set main file path
file_path <- '/home/user/EDS_Capstone_Project/US_Renewable_Energy_EDS_Capstone/US_Renewable_Energy_EDS_Capstone'
file_path

[1] "/home/user/EDS_Capstone_Project/US_Renewable_Energy_EDS_Capstone/US_Renewable_Energy_EDS_Capstone/Lesson_1:Cleaning_Data_for_Analysis/cleaned_datasets_scripts"

[1] "/home/user/EDS_Capstone_Project/US_Renewable_Energy_EDS_Capstone/US_Renewable_Energy_EDS_Capstone/Lesson_1:Cleaning_Data_for_Analysis"

[1] "/home/user/EDS_Capstone_Project/US_Renewable_Energy_EDS_Capstone/US_Renewable_Energy_EDS_Capstone"

In [4]:
#load in packages
library(tidyverse)

#load in raw data
total_energy <- read.csv(file.path(file_path, "raw_data/Total_State_Energy_Consumption_(billion_BTU).csv"))
renewable_energy <- read.csv(file.path(file_path, "raw_data/State_Renewable_Energy_Consumption_(billion_BTU).csv"))

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0

── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

In [5]:
#look at data
#head(total_energy)
head(renewable_energy)

#want years to be a variable column (Year)instead of on top
#want to change years from X####-> ####
#must delete "," in numbers

  State X1960   X1961   X1962   X1963   X1964   X1965   X1966   X1967   X1968
1 AK    4,670   5,160   5,283   5,493   5,828   6,057   6,114   5,910   5,946
2 AL    66,967  69,190  71,684  67,547  76,231  71,876  72,734  80,231  78,106
3 AR    40,817  41,049  40,059  38,411  38,775  38,819  40,584  37,500  43,993
4 AZ    14,214  13,847  13,645  14,064  13,932  18,841  21,495  21,267  23,609
5 CA    141,733 136,263 165,152 180,034 174,530 202,276 190,831 223,328 204,480
6 CO    9,788   9,415   9,886   10,099  10,420  9,768   10,388  10,391  10,654
  ⋯ X2014   X2015   X2016   X2017   X2018   X2019   X2020   X2021   X2022
1 ⋯ 11,523  13,526  14,371  13,136  13,694  12,952  9,757   9,597   10,410
2 ⋯ 236,143 225,388 217,520 229,887 233,969 232,118 235,538 239,817 232,035
3 ⋯ 115,127 107,425 105,871 103,841 105,007 106,732 91,389  89,714  90,825
4 ⋯ 72,405  79,520  83,630  88,295  92,790  92,495  90,813  99,266  101,215
5 ⋯ 560,635 564,184 645,141 724,945 690,792 788,792 738,585 810,020 880,995
6 ⋯ 71,727  76,060  86,993  88,198  90,564  98,087  95,342  103,955 114,917
  X2023
1 10,087
2 222,189
3 87,277
4 108,445
5 1,065,179
6 115,061

In [6]:
#PIVOT LONGER to get duplicate states
#want State in first column, Year in second column, energy consumption in third row

total_energy_long <- total_energy %>%
  pivot_longer(
    cols = 2:65, #duplicates the state and keeps it in the first column
    names_to = "Year", #variable for headings
    values_to = "Total_Energy" #variables for observations
  ) %>%
  mutate(Year = str_replace(Year, "[X]", "")) %>% #deletes X in front of year
  mutate(Total_Energy = as.numeric(str_replace_all(Total_Energy, ",", ""))) #char -> num and deletes ","s in number
    
#total_energy_long

renewable_energy_long <- renewable_energy %>%
  pivot_longer(
    cols = 2:65, #duplicates the state and keeps it in the first column
    names_to = "Year", #variable for headings
    values_to = "Renewable_Energy" #variables for observations
  ) %>%
  mutate(Year = str_replace(Year, "[X]", "")) %>% #deletes X in front of year
  mutate(Renewable_Energy = as.numeric(str_replace_all(Renewable_Energy, ",", ""))) #char -> num & deletes ","s in number
    
head(renewable_energy_long)

  State Year Renewable_Energy
1 AK    1960 4670
2 AK    1961 5160
3 AK    1962 5283
4 AK    1963 5493
5 AK    1964 5828
6 AK    1965 6057

In [8]:
#join the two datasets together by State and Year

energy_consumption <- total_energy_long %>%
    full_join(renewable_energy_long, by = c("State", "Year")) %>%
    mutate(NonRenewable_Energy = Total_Energy - Renewable_Energy) %>%

    #percentages
    mutate(NonRenewable_Percent = round((NonRenewable_Energy/Total_Energy)*100)) %>%    
    mutate(Renewable_Percent = round((Renewable_Energy/Total_Energy)*100)) %>% 

    #ordered
    select(State, Year, Total_Energy, NonRenewable_Energy, NonRenewable_Percent, Renewable_Energy, Renewable_Percent)

energy_consumption
#WV and WY are there!!

     State Year Total_Energy NonRenewable_Energy NonRenewable_Percent
1    AK    1960  59303        54633              92
2    AK    1961  70020        64860              93
3    AK    1962  76642        71359              93
4    AK    1963  78488        72995              93
5    AK    1964  82793        76965              93
6    AK    1965  85319        79262              93
7    AK    1966 100481        94367              94
8    AK    1967 112625       106715              95
9    AK    1968 119992       114046              95
10   AK    1969 154232       148176              96
11   AK    1970 179470       173203              97
12   AK    1971 198395       191869              97
13   AK    1972 211964       205703              97
14   AK    1973 194968       189121              97
15   AK    1974 199194       193159              97
16   AK    1975 229676       223564              97
17   AK    1976 251979       245447              97
18   AK    1977 289893       282040              97
19   AK    1978 320731       313201              98
20   AK    1979 296592       289042              97
21   AK    1980 291985       287423              98
22   AK    1981 275504       270444              98
23   AK    1982 405103       400312              99
24   AK    1983 433409       428036              99
25   AK    1984 478019       471737              99
26   AK    1985 469166       462646              99
27   AK    1986 498563       493544              99
28   AK    1987 493105       487208              99
29   AK    1988 514932       508637              99
30   AK    1989 570067       557850              98
⋮    ⋮     ⋮    ⋮            ⋮                   ⋮
3299 US    1994 87080163     83023690            95
3300 US    1995 88732046     84435404            95
3301 US    1996 91474194     86992696            95
3302 US    1997 92105715     87644822            95
3303 US    1998 92614839     88442110            95
3304 US    1999 94212808     90011082            96
3305 US    2000 96686060     92590424            96
3306 US    2001 94391208     90874899            96
3307 US    2002 95582476     91816321            96
3308 US    2003 95806580     91890696            96
3309 US    2004 98044608     93939080            96
3310 US    2005 98108764     93877403            96
3311 US    2006 97231383     92751123            95
3312 US    2007 98987749     94392922            95
3313 US    2008 96657598     91589950            95
3314 US    2009 91630574     86338101            94
3315 US    2010 95129103     89233467            94
3316 US    2011 93969435     87661952            93
3317 US    2012 91664394     85514429            93
3318 US    2013 94234417     87647920            93
3319 US    2014 95322209     88526712            93
3320 US    2015 94462877     87640682            93
3321 US    2016 94072893     86963435            92
3322 US    2017 93892854     86519594            92
3323 US    2018 97391985     89866584            92
3324 US    2019 96564778     88979666            92
3325 US    2020 88857658     81567589            92
3326 US    2021 93350300     85704133            92
3327 US    2022 94831564     86724211            91
3328 US    2023 93557489     85370172            91
     Renewable_Energy Renewable_Percent
1     4670            8
2     5160            7
3     5283            7
4     5493            7
5     5828            7
6     6057            7
7     6114            6
8     5910            5
9     5946            5
10    6056            4
11    6267            3
12    6526            3
13    6261            3
14    5847            3
15    6035            3
16    6112            3
17    6532            3
18    7853            3
19    7530            2
20    7550            3
21    4562            2
22    5060            2
23    4791            1
24    5373            1
25    6282            1
26    6520            1
27    5019            1
28    5897            1
29    6295            1
30   12217            2
⋮    ⋮                ⋮
3299 4056473          5
3300 4296642          5
3301 4481498          5
3302 4460893          5
3303 4172729          5
3304 4201726          4
3305 4095636          4
3306 3516309          4
3307 3766155          4
3308 3915884          4
3309 4105528          4
3310 4231361          4
3311 4480260          5
3312 4594827          5
3313 5067648          5
3314 5292473          6
3315 5895636          6
3316 6307483          7
3317 6149965          7
3318 6586497          7
3319 6795497          7
3320 6822195          7
3321 7109458          8
3322 7373260          8
3323 7525401          8
3324 7585112          8
3325 7290069          8
3326 7646167          8
3327 8107353          9
3328 8187317          9

In [9]:
write.csv(energy_consumption, file.path(file_path, "Lesson_1:Cleaning_Data_for_Analysis/cleaned_datasets/State_Energy_Consumptions.csv"))